import Vue from 'vue'
import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faCloudUploadAlt } from '@fortawesome/free-solid-svg-icons'

import { 
  faPhoneAlt, 
  faCloudArrowUp,
  faPhone,
  faUpload,
  faArrowRight,
  faArrowRightLong,
  faFilePlus,
  faEye,
  faPeopleGroup,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faBuilding,
  faEnvelope,
  faMobileAlt,
  faUserShield,
  faBell,
  faPlane,
  faSyncAlt,
  faHeadset,
  faCertificate,
  faPaperPlane,
  faHandshake,
  faFileAlt,
  faTimes,
  faChartLine,
  faGlobe,
  faBalanceScale,
  faMapMarkerAlt,
  faStar,
  faBriefcase,
  faBullseye,
  faAward,
  faShieldAlt,
  faHardHat,
  faLightbulb,
  faClock,
  faHeart,
  faUser,
  faUsers,
  faListAlt
} from '@fortawesome/free-solid-svg-icons'
import {
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn
} from '@fortawesome/free-brands-svg-icons'

// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = false

// You can add your icons directly in this plugin. See other examples for how you
// can add other styles or just individual icons.
library.add(
  faPhoneAlt,
  faCloudArrowUp,
  faPhone,
  faUpload,
  faArrowRight,
  faArrowRightLong,
  faFilePlus,
  faEye,
  faPeopleGroup,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn,
  faBuilding,
  faEnvelope,
  faMobileAlt,
  faUserShield,
  faBell,
  faPlane,
  faSyncAlt,
  faHeadset,
  faCertificate,
  faPaperPlane,
  faHandshake,
  faFileAlt,
  faTimes,
  faChartLine,
  faGlobe,
  faBalanceScale,
  faMapMarkerAlt,
  faStar,
  faBriefcase,
  faBullseye,
  faAward,
  faShieldAlt,
  faHardHat,
  faLightbulb,
  faClock,
  faHeart,
  faUser,
  faUsers,
  faListAlt
)

// Register the component globally
Vue.component('FontAwesomeIcon', FontAwesomeIcon)


console.log({
  faPhoneAlt,
  faCloudArrowUp,
  faPhone,
  faUpload,
  faArrowRight,
  faArrowRightLong,
  faFilePlus,
  faEye,
  faPeopleGroup,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faFacebookF,
  faTwitter,
  faInstagram,
  faLinkedinIn,
  faBuilding,
  faEnvelope,
  faMobileAlt,
  faUserShield,
  faBell,
  faPlane,
  faSyncAlt,
  faHeadset,
  faCertificate,
  faPaperPlane,
  faHandshake,
  faFileAlt,
  faTimes,
  faChartLine,
  faGlobe,
  faBalanceScale,
  faMapMarkerAlt,
  faStar,
  faBriefcase,
  faBullseye,
  faAward,
  faShieldAlt,
  faHardHat,
  faLightbulb,
  faClock,
  faHeart,
  faUser,
  faUsers,
  faListAlt
})
